---

stages:
  - prepare
  - build
  - release

prepare:5.6:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:5.6
  only:
    - master

prepare:7.0:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.0
  only:
    - master

build:5.6:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 5.6; ./build.sh
  only:
    - master

build:7.0:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.0; ./build.sh
  only:
    - master

release:5.6:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-magento1:5.6
  only:
    - master

release:7.0:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-magento1:7.0
  only:
    - master
